#!/bin/bash
ls -al . ../boot
[master 6a7a92f] Task 11
 2 files changed, 3 insertions(+), 1 deletion(-)
 create mode 100644 0x00-shell_basics/11-lists
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   11-lists

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../0-iam_betty

no changes added to commit (use "git add" and/or "git commit -a")
